apiVersion: v1
kind: Secret
metadata:
  name: auto-pin-bot-secrets
  labels:
    {{- include "auto-pin-bot.labels" . | nindent 4 }}
type: "Opaque"
data:
  discordToken: {{ .Values.discordToken | b64enc | quote }}

