version: "3"

services:
  auto-pin-bot:
    container_name: auto-pin-bot
    environment:
      BOT_TOKEN: Njk4NTQ1OTM0MTcwMTk0MDEy.XpHamg.L0PdVaSTJSJLJCHGfsWA7DpUcdk
    volumes:
    - ./database.mv.db:/database.mv.db
