version: "3"

services:
  auto-pin-bot:
    image: ghcr.io/teheidoma/auto-pin-bot:latest
    container_name: auto-pin-bot
    environment:
      BOT_TOKEN: $BOT_TOKEN
    volumes:
      - ./data/:/workdir/data
