version: "3"

services:
  auto-pin-bot:
    image: docker.pkg.github.com/teheidoma/auto-pin-bot/auto-pin-bot:latest
    container_name: auto-pin-bot
    environment:
      BOT_TOKEN: $BOT_TOKEN
    command: mkdir /workdir/data
    volumes:
      ./data/:/workdir/data
