name: Java CI with Gradle

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew bootBuildImage
      - name: Docker push
        run: |
          version=$(./gradlew -q getVersion)
          docker push ghcr.io/teheidoma/auto-pin-bot:${version}
          docker tag ghcr.io/teheidoma/auto-pin-bot:${version} ghcr.io/teheidoma/auto-pin-bot:latest
          docker push ghcr.io/teheidoma/auto-pin-bot:latest
      - name: Helm Lint
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint auto-pin-bot && helm dep update auto-pin-bot
      - name: Helm install
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --install auto-pin-bot auto-pin-bot
          kubeconfig: '${{ secrets.KUBECONFIG }}'
